# Generated by Django 6.0.3 on 2026-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_submission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='academic_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
