# Generated by Django 6.0.3 on 2026-06-28 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_section_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
