# Generated by Django 6.0.3 on 2026-06-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_section_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='cabinet_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='rfid_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
