# Generated by Django 6.0.3 on 2026-06-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_accesslog_cabinet_name_accesslog_reason_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activity',
            name='allow_resubmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_score',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
