# Generated by Django 6.0.6 on 2026-06-29 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_activity_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ActivityAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='activity_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.activity')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
