# Generated by Django 6.0.3 on 2026-06-29 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_activity_instructions_activityattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='action',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='locker_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='station_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='CabinetStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('offline', 'Offline')], default='available', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_stations', to='api.section')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('locker_number', models.PositiveIntegerField()),
                ('current_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('offline', 'Offline')], default='closed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lockers', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='api.cabinetstation')),
            ],
            options={
                'ordering': ['locker_number'],
                'unique_together': {('station', 'locker_number')},
            },
        ),
    ]
