# Generated by Django 6.0.3 on 2026-07-16 02:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_accesslog_action'),
    ]

    operations = [
        # NOTE: Locker and CabinetStation models are not present in
        # the current codebase. Removing the explicit RemoveField and
        # DeleteModel operations for them to avoid apply-time
        # inconsistencies on existing databases.
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Administrator Profile',
                'verbose_name_plural': 'Administrators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Instructor Profile',
                'verbose_name_plural': 'Instructors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='locker_number',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='role',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='station_name',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_sections',
            field=models.ManyToManyField(blank=True, related_name='assigned_instructors', to='api.section'),
        ),
        migrations.AddField(
            model_name='user',
            name='instructor_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        # Deleted CabinetStation/Locker models omitted to preserve
        # compatibility with current project state.
    ]
