# Generated by Django 6.0.6 on 2026-07-16 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_locker_station'),
    ]

    operations = []
