# Generated by Django 6.0.3 on 2026-07-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_locker_station_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityattachment',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activityattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityattachment',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
