# Generated by Django 6.0.3 on 2026-07-27 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_locker_station_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDiscussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_role', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='api.activity')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
