# Generated by Django 6.0.3 on 2026-07-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_activitydiscussion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locker',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='locker',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='station',
        ),
        migrations.DeleteModel(
            name='Locker',
        ),
        migrations.DeleteModel(
            name='CabinetStation',
        ),
    ]
