# Generated by Django 6.0.6 on 2026-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_passwordresetrequest_reset_authorization_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='cabinet_handoff_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='cabinet_handoff_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='cabinet_handoff_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
