# Generated by Django 6.0.3 on 2026-09-24 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_passwordresetrequest_cabinet_handoff_claimed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCEnrollmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_uid', models.CharField(max_length=100)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('token_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_enrollment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nfc_uid', 'status'], name='api_nfcenro_nfc_uid_0dfa80_idx'), models.Index(fields=['expires_at'], name='api_nfcenro_expires_eb5b3b_idx')],
            },
        ),
    ]
