# Generated by Django 6.0.6 on 2026-10-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_cabinetsession_accesslog_nfc_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='api_accessl_nfc_uid_e4a40c_idx',
            old_name='api_accessl_nfc_uid_8d0d6c_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='api_accessl_cabinet_8928fc_idx',
            old_name='api_accessl_cabinet__fe9d83_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='api_accessl_station_b6cafa_idx',
            old_name='api_accessl_station_9f0e4b_idx',
        ),
        migrations.AlterField(
            model_name='cabinetsession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
