# Generated by Django 6.0.6 on 2026-10-03 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_api_accessl_nfc_uid_8d0d6c_idx_api_accessl_nfc_uid_e4a40c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetsession',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='cabinet_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
