# Generated by Django 6.0.6 on 2026-10-03 11:28

from django.db import migrations, models


def normalize_legacy_actions(apps, schema_editor):
    AccessLog = apps.get_model('api', 'AccessLog')
    database = schema_editor.connection.alias
    AccessLog.objects.using(database).filter(action='verify').update(action='scan')
    AccessLog.objects.using(database).filter(action='access').update(action='scan')
    AccessLog.objects.using(database).filter(action='register').update(action='registration')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_accesslog_rfid_tag'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_actions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='accesslog',
            name='image',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('scan', 'Scan'), ('open', 'Open'), ('close', 'Close'), ('registration', 'Registration')], default='scan', max_length=20),
        ),
    ]
