# Generated by Django 6.0.6 on 2026-10-03 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_accesslog_image_alter_accesslog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetsession',
            name='closing_participants',
            field=models.ManyToManyField(blank=True, related_name='closing_cabinet_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cabinetsession',
            name='workflow_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('opening', 'Opening'), ('closing', 'Closing')], default='idle', max_length=20),
        ),
    ]
