# Generated by Django 6.0.6 on 2026-10-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_cabinetsession_closing_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcenrollmentsession',
            name='cabinet_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nfcenrollmentsession',
            name='station',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
