# Generated by Django 6.0.6 on 2026-10-09 14:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_cabinetsession_unique_open_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=api.models.access_log_photo_upload_to)),
                ('capture_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('diagnostic_error', models.TextField(blank=True, default='')),
                ('access_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='api.accesslog')),
            ],
        ),
    ]
